# Generated by Django 6.0 on 2025-12-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_parcelrequest_price_parcelrequest_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelrequest',
            name='platform_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parcelrequest',
            name='rider_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
